# /tiktok-uploader/docker-compose.yml (VERSÃO PARA SWARM/PRODUÇÃO)

services:
  # O nome do serviço, ex: 'uploader'
  uploader:
    # Aponte para a imagem que você VAI criar e enviar para o Docker Hub
    # Formato: seu-usuario-dockerhub/nome-da-imagem:tag
    image: uniiatom/tiktok-uploader:1.0 
    ports:
      - "5002:5002"
    deploy:
      # Política de reinicio para o modo Swarm
      restart_policy:
        condition: on-failure